apiVersion: v1
kind: Service
metadata:
  name: phb-svc
spec:
  selector:
    app: phbapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31231
  type: NodePort
