apiVersion: apps/v1
kind: Deployment
metadata:
  name: phbapp-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phbapp
  template:
    metadata:
      labels:
        app: phbapp
    spec:
      containers:
      - name: phbapp
        image: mkushimo/phb-nginx-app:1.0.4
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: svc-phbapp
  namespace: dev 
spec: 
  type: NodePort
  selector: 
    app: phbapp
  ports: 
  - targetPort: 80
    port: 80
    nodePort: 30085
    protocol: TCP