apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=

# The values for mongo-root-username and mongo-root-password are base64 encoded.
# You can use the following command to encode your values