apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-platform.fullname" . }}-api
spec:
  type: ClusterIP
  selector:
    app: {{ include "game-platform.name" . }}-api
  ports:
    - port: 80
      targetPort: 8080
